services:
  transcriberapp:
    build: .
    image: transcriberapp:jp6
    container_name: transcriberapp
    restart: unless-stopped

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    ports:
      - "8000:8000"

    volumes:
      # Carpetas del proyecto
      - ./audios:/app/audios
      - ./outputs:/app/outputs
      - ./transcripts:/app/transcripts

    env_file:
      - .env
